### PR TITLE
Add doctype

### PR DESCRIPTION
**Pull request by Choubakawa**
_~~Based on issue #2 (Sort Links) and #5 (Generic Links).~~_

~~With this PR it will be possible to sort links as wanted and add a lot of emails and links.~~

~~A new env var is used to sort: `GLOBAL_ORDER` with value the env name of our links separate by a `,` (example: `YOUTUBE,TWITCH`). `GLOBAL_ORDER` must have every env name that we use.~~

~~For emails and links the principe is the same:~~
~~`EMAIL` and `EMAIL_TEXT` can have multiple emails split by a `,`. (`EMAIL_ALT` have been removed in favor of the split.)
For the generic links, two new env var are added: `LINK` and `LINK_TEXT`.~~

Add doctype in the generated index.html

### CODE REVIEW

**Comment by Choubakawa** [comment]
The PR will make a lot of change in the code so I will understand if you reject it :)

**Comment by timothystewart6** [comment]
Thank you! I'll have to check this out locally to be sure that it works.  Also, I want to be sure that all changes going forward are backwards compatible.  This changes the types of some ENV variables (although a string to list should be "easy").  I do want to be sure the contract doesn't need to be broken unless it's absolutely necessary.

**Comment by Choubakawa** [comment]
Hi @timothystewart6, I've updated the PR with a new commit, like you can see I remove my big change to only keep the doctype. It wasn't present anymore.

If you ask why. I've seen some conflicts and instead of fixing them I revert my commit because you will have to review the PR and I prefer you take your time on a new video instead of review my PR 😎

**Comment by timothystewart6** [comment]
@Choubakawa   Thank you so much for your contributions!  Also, than you for being considerate of my time!  I have been working on v2 on the side, if it gets to a point to where I think it's viable, I will open a PR for you to review!  Thank you again!

**Pull request merged**
