### PR TITLE
Add RSS

### PR DESCRIPTION
**Pull request by sethiele**
# Proposed Changes

Added RSS Button

- RSS Button, based on LittleLink Style
  image

Screenshot (If Applicable)

## Checklist

- [X] Tested locally
- [X] Ran `yarn ci` to test my code
- [X] Did not add any unnecessary changes
- [X] All my changes appear after other changes in each file
- [X] Included a screenshot (if adding a new button)
- [X] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
Thank you!  If you can move these changes to the end of each respective file that would be great!

**Comment by sethiele** [comment]
Thanks for mergin #507. I will merge the new master.

**Comment by timothystewart6** [comment]
Thank you!

**Comment by timothystewart6** [comment]
more lint!  `yarn lint --fix`

**Comment by timothystewart6** [comment]
Thank you!

**Pull request merged**
