### PR TITLE
feat(button): Added Lastfm

### PR DESCRIPTION
**Pull request by Frostar**
# Proposed Changes

Screen Shot 2021-12-09 at 11 33 36

## Checklist

- [x] Tested locally
- [x] Ran `yarn ci` to test my code
- [x] Did not add any unnecessary changes
- [x] All my changes appear after other changes in each file
- [x] Included a screenshot (if adding a new button)
- [x] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
Looks like there's some lint!  You can run `yarn lint --fix` locally to fix it.

**Comment by timothystewart6** [comment]
You can also run `yarn ci` to check it locally too

**Comment by Frostar** [comment]
Thanks Tim - it should be okay now. :-)

**Comment by timothystewart6** [comment]
Thank you!

**Pull request merged**
