### PR TITLE
feat(style): added shadow on buttons and avatar (#191)

### LINKED ISSUE #191: Feature Request(s): Avatar / Button | Shadows
## Shadows make this so much more enjoyable to look at than just flat buttons.

Tested and working by overriding CSS via elements and directly overriding the docker css. ( However this will break for me when new buttons are added unless I update the css manually after each update.)
### Shadow effect 
 - Gives the avatar / buttons a more pop out and stylish look.
`box-shadow: 5px 5px 5px #0000006e;`

image

## Avatar code: 
 - `/usr/src/app/build/public/static/css/client.f553e0c7.css` <<< tested on multiple instances and this seems to be the same per each docker/container for the avatar css.
``` css
.avatar{vertical-align:middle;width:128px;height:128px;box-shadow: 5px 5px 5px #0000006e;border-radius:50%}
```

## Button code: 
 - `/usr/src/app/build/public/css/brands.css`
 
Snippet code to override for `.button` - This is the only part the needs to be modified for it to apply to all buttons
``` css
.button,button{display:inline-block;text-decoration:none;height:48px;box-shadow: 5px 5px 5px #0000006e;text-align:center;vertical-align:middle;font-size:18px;width:300px;font-weight:700;line-height:48px;letter-spacing:.1px;white-space:wrap;border-radius:8px;cursor:pointer}
```

### PR DESCRIPTION
**Pull request by Choubakawa**
# Proposed Changes

-  Added box-shadow to buttons and avatar with a new env variable `DROP_SHADOW`. By default their is no shadow and 3 levels are available: `light`, `medium` and `heavy`.
- Closes #191

Screenshot (If Applicable)

**Light:**
light
light

**Medium:**
medium
medium

**Heavy:**
heavy
heavy

## Checklist

- [x] Tested locally

- [x] Ran `yarn ci` to test my code
- [x] Did not add any unnecessary changes
- [x] All my changes appear after other changes in each file
- [x] Included a screenshot (if adding a new button)
- [x] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
This is great, thank you!  How about also adding it to the avatar too?

**Comment by Choubakawa** [comment]
> This is great, thank you! How about also adding it to the avatar too?

It is, but I didn't add a screenshot for the avatar :sweat_smile:. I will do it!

**Comment by Choubakawa** [comment]
The screenshots for the avatar have been added.

**Comment by timothystewart6** [comment]
Thank you so much!

**Comment by jjjonesjr33** [comment]
This is awesome @Choubakawa, thanks for getting this added!

**Pull request merged**
