### PR TITLE
Added shadow to avatar and buttons

### LINKED ISSUE #191: Feature Request(s): Avatar / Button | Shadows
## Shadows make this so much more enjoyable to look at than just flat buttons.

Tested and working by overriding CSS via elements and directly overriding the docker css. ( However this will break for me when new buttons are added unless I update the css manually after each update.)
### Shadow effect 
 - Gives the avatar / buttons a more pop out and stylish look.
`box-shadow: 5px 5px 5px #0000006e;`

image

## Avatar code: 
 - `/usr/src/app/build/public/static/css/client.f553e0c7.css` <<< tested on multiple instances and this seems to be the same per each docker/container for the avatar css.
``` css
.avatar{vertical-align:middle;width:128px;height:128px;box-shadow: 5px 5px 5px #0000006e;border-radius:50%}
```

## Button code: 
 - `/usr/src/app/build/public/css/brands.css`
 
Snippet code to override for `.button` - This is the only part the needs to be modified for it to apply to all buttons
``` css
.button,button{display:inline-block;text-decoration:none;height:48px;box-shadow: 5px 5px 5px #0000006e;text-align:center;vertical-align:middle;font-size:18px;width:300px;font-weight:700;line-height:48px;letter-spacing:.1px;white-space:wrap;border-radius:8px;cursor:pointer}
```

### PR DESCRIPTION
**Pull request by KieranRobson**
# Proposed Changes

- Added shadow to buttons and avatar - closes #191 

Screenshot (If Applicable)
image

## Checklist

- [x] Tested locally
- [x] Ran `yarn ci` to test my code
- [x] Did not add any unnecessary changes
- [x] All my changes appear after other changes in each file
- [x] Included a screenshot (if adding a new button)
- [x] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
Hey!  Thanks!  I was thinking of making this configurable with an ENV variable, rather than forcing it on everyone.

I was also considering using the Google Material 2dp values

```css
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.20);
```

**Comment by jjjonesjr33** [comment]
Looks good 😄

**Comment by jjjonesjr33** [comment]
> Hey! Thanks! I was thinking of making this configurable with an ENV variable, rather than forcing it on everyone. Something like `DROP_SHADOW: true`
> 
> I was also considering using the Google Material 2dp values
> 
> ```css
> box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.20);
> ```
> 
> https://material.io/design/environment/light-shadows.html#shadows

@timothystewart6 I tested the box shadow that you listed, in comparison you can't really tell there is a shadow with. It's almost more of an outline?

Example with your code for shadow 
```css
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.20); 
```

image

Vs my original
```css
    box-shadow: 5px 5px 5px #0000006e;
 ```
image

Now if there was a way to have a user set their own that could be dynamic that would be awesome or even a dynamic setting like - `none`, `light`, `medium`, or `heavy` using your `DROP_SHADOW:` variable. I do like that idea!

**Comment by KieranRobson** [comment]
Will close this for now due to having no idea how to implement the above ideas 😆, if anyone has any guidance them feel free to lemme know and ill try implement it and reopen this PR 😆

**Comment by Choubakawa** [comment]
> Will close this for now due to having no idea how to implement the above ideas 😆, if anyone has any guidance them feel free to lemme know and ill try implement it and reopen this PR 😆

A way to implement it with a boolean in `DROP_SHADOW`:

Add a new CSS class in `brands.css` and `Avatar.css` or higher in `normalize.css`:

```css
.box-shadow {
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.20);
}
```

In `Button.js` and `Avatar.js` you add a new condition in `className` on `DROP_SHADOW` to add or not the class box-shadow.

it will look like this:

```css
className={  styles ? 'button' : `button button-${name}` + runtimeConfig?.DROP_SHADOW ? ' shadow' : '' }
```


To use `light`, `medium` or `heavy` instead of a boolean you can use a method, something like this (you will need to have 3 CSS classes `.box-shadow-light` / `.box-shadow-medium` / `.box-shadow-heavy`  :

```js
const addShadow = () => {
    let shadow = '';
    if (runtimeConfig?.DROP_SHADOW) {
      switch (runtimeConfig?.DROP_SHADOW) {
        case 'light':
          shadow = ' shadow-light';
          break;
        case 'medium':
          shadow = ' shadow-medium';
          break;
        case 'heavy':
          shadow = ' shadow-heavy';
          break;
        default:
          break;
      }
    }
    return shadow;
  };
```

and in className:

```css
className={  styles ? 'button' : `button button-${name}` + addShadow }
```

**Pull request closed without merging**
