### PR TITLE
Added support for Strava

### PR DESCRIPTION
**Pull request by palepinkdot**
Added support for a popular running and cycling social media app called Strava.

### CODE REVIEW

**Comment by timothystewart6** [comment]
Looks like there's some lint!  You can fix this by running

```bash
yarn lint --fix
```
locally and then committing that change

**Comment by timothystewart6** [comment]
Also, for consistency, can you add these change to the end of each file?

**Comment by palepinkdot** [comment]
> Also, for consistency, can you add these change to the end of each file?

Of course.

**Comment by timothystewart6** [comment]
Thank you.  I will add a comment in the future for EOF references.  Thank you so much!

**Pull request merged**
