### PR TITLE
Add Plausible Analytics

### PR DESCRIPTION
**Pull request by jdepumpo**
# Proposed Changes
Added Plausible Analytics 

Plausible's tags look like this:
```
<script defer data-domain="domain.com" src="https://plausible.io/js/script.js"></script>
```

If you are using their hosted version the PLAUSIBLE_URL=https://plausible.io, otherwise you can use your self-hosted URL. PLAUSIBLE_DATA_DOMAIN is the domain of your littlelink-server.

### CODE REVIEW

**Comment by timothystewart6** [comment]
Thank you!  Have you considered making the script name a variable too?  The only reason I ask is because some adblocker will can also look at `script.js`  and possibly block it or the script `script.js` name could end up changing in the future. Both are unlikely but this would add lots of flexibility if it were something like

```env
PLAUSIBLE_DOMAIN=https://example.com/
PLAUSIBLE_PATH=js/
PLAUSIBLE_SCRIPT_NAME=script.js
```



Asking because this came up recently https://github.com/techno-tim/littlelink-server/issues/372

**Comment by jdepumpo** [comment]
Hi Tim, thanks for the feedback! You're right, no reason to hardcode the /script.js path.

**Comment by timothystewart6** [comment]
Looks like CI is failing from lint.  You can fix it with `yarn lint --fix` or `npm lint --fix`

**Comment by timothystewart6** [comment]
Thank you!!!

**Pull request merged**
