### PR TITLE
fix: umami tracking

### PR DESCRIPTION
**Pull request by kdurek**
# Proposed Changes

Fix for umami new api

Screenshot (If Applicable)
CleanShot 2024-04-16 at 16 26 10

## Checklist

- [x] Tested locally
- [x] Ran `yarn ci` to test my code
- [x] Did not add any unnecessary changes
- [x] All my changes appear after other changes in each file
- [ ] Included a screenshot (if adding a new button)
- [x] Fixed one typo in `README.md`
- [x] 🚀

### CODE REVIEW

**Review by timothystewart6 — APPROVED** [review]

**Comment by timothystewart6** [comment]
Thank you so much!

**Comment by timothystewart6** [comment]
Looks like the test also needs to be fixed.

**Comment by timothystewart6** [comment]
this closes https://github.com/techno-tim/littlelink-server/issues/540

**Comment by timothystewart6** [comment]
Run `yarn ci` locally to test

**Comment by kdurek** [comment]
Yeah, working on it!

**Comment by kdurek** [comment]
@timothystewart6 done

**Pull request merged**
